### ISSUE TITLE
Is it possible to get the current folder or directory or project?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [andremacola/sublime-PHP_CBF#1]
Is it possible to get a variable with a dynamic value like the current folder, to get something like this?

```
"phpcbf_path": "{folder}phpcbf.bat",
```

**Comment by aubreypwd** [comment]
+1

**Comment by andremacola** [comment]
Hi, sorry for delay. I'm not developing in PHP anymore.
I'll try to look into this in the freetime.

**Comment by andremacola** [comment]
It turned out that I had to go back to a project using Sublime and I pushed a fix. It took a while, but it's here, haha.
